### ISSUE TITLE
Migrate Thumbnailer to new repo as namespace plugin

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/thumbnailer#1]
Refers to: https://github.com/getpelican/pelican-plugins/issues/1290

**Comment by justinmayer** [comment]
@kdeldycke: I sent you an invitation to join the `pelican-plugins` organization, which should allow you to perform the  **Initial Setup (By Maintainer)** steps in the aforementioned migration guide, as well as the **Updating the Plugin** further below that you are clearly already familiar with. 😉 

A few *very* small things, just for consistency:

* Let's use `main` as the new primary branch name for new repositories.
* We've been using capital letters for `README.md` and `CONTRIBUTING.md` throughout the plugins here, so we might as well keep doing so for consistency.
* Since issue titles, PR titles, and commit messages are almost never complete sentences (or surrounded by other text), it's usually not necessary to end them with a period. (Unless there are multiple actual sentences within, of course.)

Many thanks again for helping out with this. 🙏 Let me know if you have any questions!

**Comment by kdeldycke** [comment]
Thanks @justinmayer for the invitation!

1. Great initiative of having `main` as the primary branch name. Also need to make that change on my own repo by the way. 😉 
2. Sorry for that tweak in `neighbors`. I just don't like files screaming at me! 😆 I'll keep the uppercase for consistency between plugins.
3. Ahah, sorry for that old habit of mine. I'll refrain adding periods where it doesn't make sense.

I'll applies all the rules you stated for pelican plugins and proceed with the migration in the next few days.

**Comment by justinmayer** [comment]
Awesome! I know what you mean about the "screaming" appearance. Not an easy call either way.

Thanks again!

**Comment by kdeldycke** [comment]
TODO:
* [ ] Add repository description: `Thumbnailer is a Pelican plugin creates smaller versions of images found in a directory`.
