### ISSUE TITLE
Installation fails on Windows with Python 3.12

### ISSUE THREAD

**Issue by mikolajgolunski** [pelican-plugins/thumbnailer#10]
Plugin tries to install Pillow 7.2 (Pillow<8.0,>=7.2), but this version does not support Python 3.12. Building Pillow from source on Windows is not recommended (and, if I remember correctly, it can be pretty troublesome). It would be nice to upgrade dependency to Pillow >= 10.1.

**Comment by justinmayer** [comment]
Hi Mikołaj. The Pillow dependency specification for this plugin was updated in `main` last year to `Pillow>=9.5,<10`, but this change has not yet been shipped in a packaged release to PyPI. Hopefully that can be remedied soon.

As for upgrading Pillow to >= 10.1, the current test suite fails on that version with `AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'`. If you would like to help out with fixing that problem, that would be most helpful. 😊

**Comment by mikolajgolunski** [comment]
Added a quick pull request. Hopefully it will be enough. Didn't have time to check it properly.

**Comment by justinmayer** [comment]
I just released v1.0.1 of the Thumbnailer plugin, which should now no longer have an upper bound on the Pillow dependency version.

Thanks again for your assistance!
